### ISSUE TITLE
Broken search in various pdf readers for "Theorem 7.1"

### ISSUE THREAD

**Issue by bellecp** [vtex-soft/texsupport.ims-aos#1]
Using the Evince pdf reader, searching for the text string "Theorem 7.1" in the sample pdf file https://github.com/vtex-soft/texsupport.ims-aos/blob/master/aos-sample.pdf does not find Theorem 7.1.
However, searching for "heorem 7.1" without the capital T finds the theorem. This suggests that some invisible character or other issue is present between T and "heorem 7.1".

**Comment by bellecp** [comment]
It appears that most published version of AOS papers in recent years suffer from this. It should be an easy-fix and very useful to quickly locate theorems in published papers. I am happy to test a possible fix in some PDF readers.

**Comment by bellecp** [comment]
Annals of Probability suffers from the same issue with the sample pdf in https://github.com/vtex-soft/texsupport.ims-aop/blob/master/aop-sample.pdf

**Comment by edgaras-sakuras** [comment]
This problem is related with two things: 

1)  LaTeX engine in general adds some kerning (space) between letters for so called visual tuning. 
    For small caps too. And this "fix-up" is even font dependent, e.g. compiling this file:

    ```LaTeX
    \documentclass{article}
    \begin{document}
    \textsc{Theorem 7.1}
    \end{document}
    ```

    would result PDF with searchable "theo" (by Evince). In this case default Computer Modern font is used.
    But adding these two line before `\begin{document}`:

    ```LaTeX
    \usepackage[T1]{fontenc}
    \usepackage{times}
    ```

    would result PDF with **non**-searchable "theo" (by Evince). In this case default Nimbus Roman is used.

2)  Not all PDF viewers "understand" such pseudo spaces (bug or feature in heuristics?).
    Usually these are PDF viewers with Poppler based PDF rendering - Evince, Zathura, Qpdfview, etc.
