### ISSUE TITLE
Reference order

### ISSUE THREAD

**Issue by nhavt** [vtex-soft/texsupport.ims-aos#3]
Hello edgaras-sakuras,

I have a question regarding references sorted according to authors and years. I think there might be a bug in a sort algorithm for references, see my sample LaTeX code below. Could you please have a look at this? Thanks in advance! 

``\documentclass[aos]{imsart}
\RequirePackage[numbers]{natbib}
\RequirePackage{url}
\begin{document}
\begin{frontmatter}
\title{Reference order}
\end{frontmatter}

The correct order for references should be:\\

\string\citet: \citet{Bailey2004}\par
\string\citet: \citet{Bailey2008}\par
\string\citet: \citet{Bailey2020}\par
\string\citet: \citet{Bailey1997}\par
\string\citet: \citet{BaileyRF2019}\par
\string\citet: \citet{Smith2015}\par
\string\citet: \citet{Smith2006}\par
\bibliographystyle{imsart-nameyear}
\bibliography{sample}
\end{document}``

``@Book{Bailey2004,
	title={Association {S}chemes: Designed {E}xperiments, {A}lgebra and {C}ombinatorics},
	author={Bailey, Rosemary A},
	series ={Cambridge Studies in Advanced Mathematics 84},
	year={2004},	
	publisher={Cambridge University Press, Cambridge}
}
@Book{Bailey2008,
	author    = {Bailey, Rosemary A},
	publisher = {Cambridge University Press, Cambridge},
	title     = {Design of Comparative Experiments},
	year      = {2008}
}
@Article{Smith2015,
	author    = {Smith, Alison B and Butler, David G and Cavanagh, Colin R and Cullis, Brian R},
	journal   = {The Journal of Agricultural Science},
	title     = {Multi-phase variety trials using both composite and individual replicate samples: {A} model-based design approach},
	year      = {2015},
	pages     = {1017--1029},
	volume    = {153},
	publisher = {Cambridge University Press},
}
@Article{Smith2006,
	title={The design and analysis of multi-phase plant breeding experiments},
	author={Smith, A B and Lim, P and Cullis, Brian R},
	journal={The {Journal} of {A}gricultural {S}cience},
	volume={144},
	pages={393--409},
	year={2006},
	publisher={Cambridge University Press}
}
@Misc{BaileyRF2019,
	author = {Bailey, R F},
	title = {Distance{R}egular.org},	
	year = {2019},
	note = {\url{http://www.distanceregular.org/}}
}
@article{Bailey1997,
	title={Optimal semi-Latin squares with side six and block size two},
	author={Bailey, R A and Royle, Gordon},
	journal={Proceedings of the Royal Society, Series A},
	volume={453},
	pages={1903--1914},
	year={1997},
	publisher={The Royal Society}
}

@article{Bailey2020,
	author    = {Bailey, Rosemary Anne and Cameron, Peter J and Soicher, L H and Williams, E R},
	journal   = {Journal of Agricultural, Biological and Environmental Statistics},
	volume    = {25},
	title     = {Substitutes for the non-existent square lattice designs for 36 varieties},
	year      = {2020},
	pages={487--499},
	publisher = {Springer}
}
``

**Comment by edgaras-sakuras** [comment]
Hello,

it's a bit tricky situation, because sorting algorithms of  `imsart-nameyear bst` and `imsart-number.bst` differ. And the reference order with the later is the one that you want. I've asked our production manager what would happen and he assured that `number` sorting will be used.

**Comment by nhavt** [comment]
Hello edgaras-sakuras, thanks for your explanation. But I think there is still a bug in the sorting algorithm of "imsart-nameyear.bst". Because this sorting algorithm will sort "authors" followed by "years", I suppose? What about the sorting rule in "imsart-number"? Is it also based also "an author" and "a year"?

**Comment by edgaras-sakuras** [comment]
Ok, lets list sorting strings in both cases. `nameyear`:
```
bailey      2004
bailey      2008
smith  zzz       2015
smith  lim  2006  cullis      2006
bailey      2019
bailey  royle  1997      1997
bailey  zzz       2020
```

**Comment by edgaras-sakuras** [comment]
`number`:
```
bailey r a       2004
bailey r a       2008
smith a b   butler d g   cavanagh c r   cullis b r       2015
smith a b   lim p   cullis b r       2006
bailey r f       2019
bailey r a   royle g       1997
bailey r a   cameron p j   soicher l h   williams e r       2020
```

**Comment by edgaras-sakuras** [comment]
And these rules (years ago) were given by (or agreed with) journal editor.  It may look strange because your usage of referencing is interesting: citation type is `number` with elements (and sorting) from `nameyear`. I don't know if journal style will let it. But one can not be ever sure till the article is published 😃
