### ISSUE TITLE
slow bibtex with many co-authors

### ISSUE THREAD

**Issue by JohannesBuchner** [vtex-soft/texsupport.ims-aos#5]
With a imsart-nameyear bibtex style, including a entry with many co-authors such as https://ui.adsabs.harvard.edu/abs/2023PhRvX..13a1048A/exportcitation is very slow when running bibtex. It also causes other issues https://bugs.launchpad.net/ubuntu/+source/lyx/+bug/2069792 

Perhaps the bst code can be improved for cases with a large number of co-authors.

**Comment by lstonys** [comment]
In traditional bibtex styles person parts are formatted directly via one procedure for example `s nameptr "{ff~}{vv~}{ll}{, jj}" format.name$`. In this style there is a lot off additional tasks to get correct tagging and fix some typing for every person part (`first name`, `surname`, `prefix`, `suffix`). Bibtex is very limited scripting language so not much can be done for this rear case.
